openapi: 3.0.0
info:
  title: GardenHolic API
  description: |
    This API provides sensor data from the KidBright board at Ploy's house. 
    Also, it provides and analyzes weather data information from 
    Thai Meteorological Department (TMD) API.
  version: 1.0.0
servers:
  - url: /gardenholic-api/v1
paths:
  /sensors:
    get:
      summary: Returns a list of sensor data.
      operationId: controller.get_kidbright_sensors_data
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Sensor'
  /tmb_accuracy/sensors:
    get:
      summary: Compare forecast and sensors data for the past 3 days and calculate accuracy.
      operationId: controller.calculate_mape_sensors
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Accuracy'
  /tmb_accuracy:
    get:
      summary: Compare forecast and actual data for the past 3 days and calculate accuracy.
      operationId: controller.calculate_forecast_actual
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Accuracy'
  
                
components:
  schemas:
    Sensor:
      type: object
      properties:
        time:
          type: string
        lat:
          type: number
        lon:
          type: number
        soil:
          type: number
        humidity:
          type: number
        temperature:
          type: number
        light:
          type: number
    Accuracy:
       type: object
       properties:
          humidity_accuracy_percentage:
            type: integer
          temperature_accuracy_percentage:
            type: integer
    Forecast:
      type: object
      properties:
        time:
          type: string
        lat:
          type: number
        lon:
          type: number
        humidity:
          type: number
        temperature:
          type: number