openapi: 3.0.0
info:
  title: GardenHolic API
  description:
    This API provides sensor data from kidbright board at Ploy's house. 
    Also, it provides and analyses weather data information from 
    Thai Meteorological Department (TMD) API.
  version: 1.0.0
servers:
- url: /gardenholic-api/v1
paths:
  /sensors:
    get:
      summary: Returns a list of sensor data.
      operationId: controller.get_kidbright_sensors_data
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Sensor'
  /should_I_water_my_plant:
    get:
      summary: Returns boolean wheter user should water their plant or not
      operationId: controller.get_remind_water_my_plant
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/WaterPlant'

components:
  schemas:
    Sensor:
      type: object
      properties:
        time:
          type: string
        lat:
          type: number
        lon:
          type: number
        soil:
          type: number
        humidity:
          type: number
        temperature:
          type: number
        light:
          type: number

    CurrentSoil:
      type: object
      properties:
        time:
          type: string
        soil:
          type: number

    ForcastHumid:
      type: object
      properties:
        time:
          type: string
        humid:
          type: number

    WaterPlant:
      type: object
      properties:
        water:
          type: string
