# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class CurrentSoil(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, time: str=None, soil: float=None):  # noqa: E501
        """CurrentSoil - a model defined in Swagger

        :param time: The time of this CurrentSoil.  # noqa: E501
        :type time: str
        :param soil: The soil of this CurrentSoil.  # noqa: E501
        :type soil: float
        """
        self.swagger_types = {
            'time': str,
            'soil': float
        }

        self.attribute_map = {
            'time': 'time',
            'soil': 'soil'
        }
        self._time = time
        self._soil = soil

    @classmethod
    def from_dict(cls, dikt) -> 'CurrentSoil':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CurrentSoil of this CurrentSoil.  # noqa: E501
        :rtype: CurrentSoil
        """
        return util.deserialize_model(dikt, cls)

    @property
    def time(self) -> str:
        """Gets the time of this CurrentSoil.


        :return: The time of this CurrentSoil.
        :rtype: str
        """
        return self._time

    @time.setter
    def time(self, time: str):
        """Sets the time of this CurrentSoil.


        :param time: The time of this CurrentSoil.
        :type time: str
        """

        self._time = time

    @property
    def soil(self) -> float:
        """Gets the soil of this CurrentSoil.


        :return: The soil of this CurrentSoil.
        :rtype: float
        """
        return self._soil

    @soil.setter
    def soil(self, soil: float):
        """Sets the soil of this CurrentSoil.


        :param soil: The soil of this CurrentSoil.
        :type soil: float
        """

        self._soil = soil
