# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ForcastHumid(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, time: str=None, humid: float=None):  # noqa: E501
        """ForcastHumid - a model defined in Swagger

        :param time: The time of this ForcastHumid.  # noqa: E501
        :type time: str
        :param humid: The humid of this ForcastHumid.  # noqa: E501
        :type humid: float
        """
        self.swagger_types = {
            'time': str,
            'humid': float
        }

        self.attribute_map = {
            'time': 'time',
            'humid': 'humid'
        }
        self._time = time
        self._humid = humid

    @classmethod
    def from_dict(cls, dikt) -> 'ForcastHumid':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ForcastHumid of this ForcastHumid.  # noqa: E501
        :rtype: ForcastHumid
        """
        return util.deserialize_model(dikt, cls)

    @property
    def time(self) -> str:
        """Gets the time of this ForcastHumid.


        :return: The time of this ForcastHumid.
        :rtype: str
        """
        return self._time

    @time.setter
    def time(self, time: str):
        """Sets the time of this ForcastHumid.


        :param time: The time of this ForcastHumid.
        :type time: str
        """

        self._time = time

    @property
    def humid(self) -> float:
        """Gets the humid of this ForcastHumid.


        :return: The humid of this ForcastHumid.
        :rtype: float
        """
        return self._humid

    @humid.setter
    def humid(self, humid: float):
        """Sets the humid of this ForcastHumid.


        :param humid: The humid of this ForcastHumid.
        :type humid: float
        """

        self._humid = humid
