# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class HumidTempData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, time: str=None, lat: float=None, lon: float=None, humidity: float=None, temperature: float=None):  # noqa: E501
        """HumidTempData - a model defined in Swagger

        :param time: The time of this HumidTempData.  # noqa: E501
        :type time: str
        :param lat: The lat of this HumidTempData.  # noqa: E501
        :type lat: float
        :param lon: The lon of this HumidTempData.  # noqa: E501
        :type lon: float
        :param humidity: The humidity of this HumidTempData.  # noqa: E501
        :type humidity: float
        :param temperature: The temperature of this HumidTempData.  # noqa: E501
        :type temperature: float
        """
        self.swagger_types = {
            'time': str,
            'lat': float,
            'lon': float,
            'humidity': float,
            'temperature': float
        }

        self.attribute_map = {
            'time': 'time',
            'lat': 'lat',
            'lon': 'lon',
            'humidity': 'humidity',
            'temperature': 'temperature'
        }
        self._time = time
        self._lat = lat
        self._lon = lon
        self._humidity = humidity
        self._temperature = temperature

    @classmethod
    def from_dict(cls, dikt) -> 'HumidTempData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The HumidTempData of this HumidTempData.  # noqa: E501
        :rtype: HumidTempData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def time(self) -> str:
        """Gets the time of this HumidTempData.


        :return: The time of this HumidTempData.
        :rtype: str
        """
        return self._time

    @time.setter
    def time(self, time: str):
        """Sets the time of this HumidTempData.


        :param time: The time of this HumidTempData.
        :type time: str
        """

        self._time = time

    @property
    def lat(self) -> float:
        """Gets the lat of this HumidTempData.


        :return: The lat of this HumidTempData.
        :rtype: float
        """
        return self._lat

    @lat.setter
    def lat(self, lat: float):
        """Sets the lat of this HumidTempData.


        :param lat: The lat of this HumidTempData.
        :type lat: float
        """

        self._lat = lat

    @property
    def lon(self) -> float:
        """Gets the lon of this HumidTempData.


        :return: The lon of this HumidTempData.
        :rtype: float
        """
        return self._lon

    @lon.setter
    def lon(self, lon: float):
        """Sets the lon of this HumidTempData.


        :param lon: The lon of this HumidTempData.
        :type lon: float
        """

        self._lon = lon

    @property
    def humidity(self) -> float:
        """Gets the humidity of this HumidTempData.


        :return: The humidity of this HumidTempData.
        :rtype: float
        """
        return self._humidity

    @humidity.setter
    def humidity(self, humidity: float):
        """Sets the humidity of this HumidTempData.


        :param humidity: The humidity of this HumidTempData.
        :type humidity: float
        """

        self._humidity = humidity

    @property
    def temperature(self) -> float:
        """Gets the temperature of this HumidTempData.


        :return: The temperature of this HumidTempData.
        :rtype: float
        """
        return self._temperature

    @temperature.setter
    def temperature(self, temperature: float):
        """Sets the temperature of this HumidTempData.


        :param temperature: The temperature of this HumidTempData.
        :type temperature: float
        """

        self._temperature = temperature
