# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class WaterPlant(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, water: str=None):  # noqa: E501
        """WaterPlant - a model defined in Swagger

        :param water: The water of this WaterPlant.  # noqa: E501
        :type water: str
        """
        self.swagger_types = {
            'water': str
        }

        self.attribute_map = {
            'water': 'water'
        }
        self._water = water

    @classmethod
    def from_dict(cls, dikt) -> 'WaterPlant':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The WaterPlant of this WaterPlant.  # noqa: E501
        :rtype: WaterPlant
        """
        return util.deserialize_model(dikt, cls)

    @property
    def water(self) -> str:
        """Gets the water of this WaterPlant.


        :return: The water of this WaterPlant.
        :rtype: str
        """
        return self._water

    @water.setter
    def water(self, water: str):
        """Sets the water of this WaterPlant.


        :param water: The water of this WaterPlant.
        :type water: str
        """

        self._water = water
